FROM php:7.4-apache

RUN /usr/sbin/a2enmod rewrite \
 && /usr/sbin/a2enmod headers \
 && /usr/sbin/a2enmod expires

RUN apt-get update \
 && apt-get install libldap2-dev libzip-dev libicu-dev libpng-dev -y \
 && rm -rf /var/lib/apt/lists/* \
 && docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/ \
 && docker-php-ext-install ldap

RUN pecl install xdebug-3.0.3 \
 && docker-php-ext-enable xdebug \
 && docker-php-ext-install pdo pdo_mysql \
 && docker-php-ext-install gd
