version: "3.9"
services:
  app:
    build:
      context: ./..
      dockerfile: docker/php/dockerfile
    container_name: coordinator-framework-app
    volumes:
      - ./..:/var/www/html
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - "8080:80"
  db:
    image: mysql:5.7
    container_name: coordinator-framework-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: developer
      MYSQL_PASSWORD: developer
    volumes:
      - ./mysql/.data:/var/lib/mysql
    ports:
      - "33060:3306"
