version: "3.9"
services:
  nginx:
    build: ./nginx/
    container_name: coordinator-framework-nginx
    ports:
      - "8080:80"
    volumes:
      - ./../:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - phpfpm
  phpfpm:
    build: ./php/
    container_name: coordinator-framework-phpfpm
    volumes:
      - ./../:/var/www/html
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    links:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: coordinator-framework-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: developer
      MYSQL_PASSWORD: developer
    volumes:
      - ./mysql/.data:/var/lib/mysql
    ports:
      - "33060:3306"
